apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: dev-01
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /same
            pathType: Exact
            backend:
              service:
                name: app-svc
                port:
                  number: 3000
          - path: /ingress
            pathType: Exact
            backend:
              service:
                name: app-svc
                port:
                  number: 3000
